{% set name = "anywidget" %}
{% set version = "0.9.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/anywidget-{{ version }}.tar.gz
  sha256: c655455bf51f82182eb23c5947d37cc41f0b1ffacaf7e2b763147a2332cb3f07

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-jupyter-builder
    - jupyterlab
    - pip
  run:
    - python >={{ python_min }}
    - ipywidgets >=7.6.0
    - typing_extensions >=4.2.0
    - psygnal >=0.8.1

test:
  imports:
    - anywidget
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/anywidget/
  summary: simple, custom Jupyter widgets
  description: |
    anywidget is a new Python library that greatly simplifies creating and publishing 
    custom Jupyter Widgets. Unlike the traditional (cookiecutter) approach, with 
    anywidget you 1) avoid fiddling with build steps and bundlers, 2) can prototype 
    widgets from within a notebook, and 3) get a modern front-end developer experience. 
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/manzt/anywidget

extra:
  recipe-maintainers:
    - manzt
    - giswqs
