{% set name = "anywidget" %}
{% set version = "0.9.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/anywidget-{{ version }}.tar.gz
  sha256: c655455bf51f82182eb23c5947d37cc41f0b1ffacaf7e2b763147a2332cb3f07

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - ipywidgets >=7.6.0
    - importlib-metadata  # [py<38]
    - typing_extensions >=4.2.0
    - psygnal >=0.8.1

test:
  imports:
    - anywidget
  commands:
    - pip check
  requires:
    - pip

about:
  summary: custom jupyter widgets made easy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - manzt
    - giswqs
